[package]
name = "compilo"
version = "0.1.0"
authors = ["valentin.rio <valentin.rio@wiztivi.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
